### ISSUE TITLE
package minimizes app in certain conditions

### ISSUE THREAD

**Issue by GabrielCR99** [Mastersam07/livechat#10]
Hello there!
So, I've been using livechatt package for some time, and, recently, I've found a bug that is kind of annoying in it. 
The thing is, whenever the user is using the app, and if it, by any case, open livechatt and minimizes it, it'll minimize the app forever.
The user can't go back to the app if it's not "killed" i.e, closed.  I've tried many times clicking on the minus (-) button that appears at the top left corner of the livechatt app screen, but it just minimizes the whole app, not only livechatt.

**Comment by Mastersam07** [comment]
Hello @GabrielCR99 were you able to fix your issue?

**Comment by Mastersam07** [comment]
Closing this since there is no engagement.
