### ISSUE TITLE
Support customParamsMap

### ISSUE THREAD

**Issue by bubupro9x** [Mastersam07/livechat#16]
Hi, 
I have an issue related pass parameter to LiveChat SDK.
And I have a solution for it.  Would u like to I create Pull request for this issue ?

Thanks u

**Comment by Mastersam07** [comment]
Sure. Pull requests are welcomed.

**Comment by naikdp7** [comment]
have you created a PR @bubupro9x or can we point to your repo if you have manage to create one?

**Comment by Mastersam07** [comment]
@bubupro9x we didn't hear from you anymore.

**Comment by Mastersam07** [comment]
Hello, @bubupro9x @naikdp7 custom params is coming to this plugin. You can track the ongoing work at #20. 

Currently, it works and is stable on android. Should be stable on ios soon. A new version is cooking

**Comment by naikdp7** [comment]
Hi,

I have already added that and created a plugin as well visit my
GitHub account

Thanks
Deep Naik

**Comment by Mastersam07** [comment]
Great work @naikdp7 . You could have sent a PR instead. Looking at your work, that's a lot. 

Editing the chat-window-ios to add the argument for customParams. Makes sense plus implementation is easier. Though there is a setVariable on LiveChat to use the customParams. Any reason why you didn't use that?

Published a new version containing this so I am closing this issue.
