### ISSUE TITLE
Deprecation of v3.1 in LiveChat APIs and SDKs

### ISSUE THREAD

**Issue by sandunangelo** [Mastersam07/livechat#18]
Hi @Mastersam07,

Hope you received this same email from LiveChat about their upcoming upgrade. My app is using your livechatt flutter package, hence I would like if the package keeps aligned with these upgrades without causing issues.

**Quoted from email;**

> ... reaching out to inform you that we’ll drop support of v3.1 in LiveChat APIs and SDKs at the end of March 2022. The change concerns the following services:
•	[the Agent Chat API ](https://livechat.apms5.com/anywhere/m?s=livechat&m=s_7b5d1695-a51e-4064-b7ac-df3a28ce6ec7&u=e1jq4wvfdtfmac1r68wkjhhm5mu34dtm5mu3gc9t5n138e215n0mchhg752k4e1q8h0m8&r2=d1u78w3k78qjyt35etjprvvgcnt76bkcd5v6arv8c5u2wrvfdmqp8vv3ecqputbkedgpeubecwqp2tv5dtu2urv8c5u2urbgd4qp6u31dtkpav3fcw&n=1)
•	[the Customer Chat API](https://livechat.apms5.com/anywhere/m?s=livechat&m=s_7b5d1695-a51e-4064-b7ac-df3a28ce6ec7&u=e1jq4wvfdtfmac1r68wkjhhm5mu34dtm5mu3gc9t5n138e215n0mchhg752k4e1q8h0m8&r2=d1u78w3k78qjyt35etjprvvgcnt76bkcd5v6arv8c5u2wrvfdmqp8vv3ecqputbkedgpeubecwqp6xbkehqputbj5nhpgrbm5ngq0u9fcdm62vk7cnp6ytr&n=2)
•	[the Configuration API](https://livechat.apms5.com/anywhere/m?s=livechat&m=s_7b5d1695-a51e-4064-b7ac-df3a28ce6ec7&u=e1jq4wvfdtfmac1r68wkjhhm5mu34dtm5mu3gc9t5n138e215n0mchhg752k4e1q8h0m8&r2=d1u78w3k78qjyt35etjprvvgcnt76bkcd5v6arv8c5u2wrvfdmqp8vv3ecqpurbec5kpavb5dtu2yrv8c5q6etbcdxkg&n=3)
•	[LiveChat JavaScript SDK](https://livechat.apms5.com/anywhere/m?s=livechat&m=s_7b5d1695-a51e-4064-b7ac-df3a28ce6ec7&u=e1jq4wvfdtfmac1r68wkjhhm5mu34dtm5mu3gc9t5n138e215n0mchhg752k4e1q8h0m8&r2=d1u78w3k78qjyt35etjprvvgcnt76bkcd5v6arv8c5u2wrvfdmqp8vv3ecqputbkedgpeubecwqpmwtdedj6p&n=4)
•	[LiveChat Go SDK ](https://livechat.apms5.com/anywhere/m?s=livechat&m=s_7b5d1695-a51e-4064-b7ac-df3a28ce6ec7&u=e1jq4wvfdtfmac1r68wkjhhm5mu34dtm5mu3gc9t5n138e215n0mchhg752k4e1q8h0m8&r2=d1u78w3k78qjyt35etjprvvgcnt76bkcd5v6arv8c5u2wrvfdmqp8vv3ecqputbkedgpeubecwqpevtdedj6p&n=5)
>
> Make sure to migrate your application to the current stable API version by 31-03-2022.

Thanks!

**Comment by Mastersam07** [comment]
Hello @sandunangelo,

I am aware of the upgrade. Having looked into it, I am not sure the upgrade to the above-mentioned services would affect this plugin. Under the hood, the plugin uses the chat-widget available at [extending-chat-widget](https://developers.livechat.com/docs/extending-chat-widget)

However, having visited the SDK's repository, new versions of the chat widget SDK have been released(no breaking changes 😃). However, I look to updating this plugin to match the latest SDK version in the coming weeks.

**Comment by sandunangelo** [comment]
Perfect! happy to hear that. Thank you for the quick response and keeping an eye on upgrades.

**Comment by Mastersam07** [comment]
@sandunangelo I just released a new version of this plugin matching the native chat widget SDK. The minimum iOS version is now 11.0 apart from that, no breaking changes.

**Comment by sandunangelo** [comment]
@Mastersam07 Awesome!!! thanks for the rapid actions you have taken to keep the plugin up to date with the vendor updates. Good job!
