### ISSUE TITLE
Livechat.beginChat() method crashes the app

### ISSUE THREAD

**Issue by sandunangelo** [Mastersam07/livechat#23]
Hi @Mastersam07,

I am in the middle of upgrade livechatt package to v1.4.0 and I have first upgraded the flutter app minimum iOS target as 11.0, and the app is working fine. Then I have upgraded the livechatt to v1.4.0 then also the app is running fine except, calling the Livechat.beginChat(...) causes the app to get crashed (even the debug app is disconnecting)

Breakpoint hits below statement and the values are valid as before when working with older versions.
`Livechat.beginChat(LICENSE_NO, GROUP_ID, VISITOR_NAME, VISITOR_EMAIL);`

All arguments have values and nothing is null.

Below is the only error (info) I get in developer console.
`Could not cast value of type 'NSNull' (0x....) to 'NSDictionary' (0x.....).`

Can you help me to resolve this issue?

Thanks!

**Comment by Mastersam07** [comment]
Hi @sandunangelo can you please show the full error gotten in your console?

**Comment by sandunangelo** [comment]
```
Could not cast value of type 'NSNull' (0x7fff86b92b38) to 'NSDictionary' (0x7fff86b92700).
Lost connection to device.
Exited (sigterm)
```

App opens and works without errors and the above error occurs when `Livechat.beginChat()` method calling. Even the debug app gets killed, thats why the `Lost connection to device` appear. Tried with a try-catch block, but not reaching the catch block as the app gets killed.

**Comment by sandunangelo** [comment]
Hey @Mastersam07,

I found the issue and a workaround from consumer end.

`Livechat.beginChat(LICENSE_NO, GROUP_ID, VISITOR_NAME, VISITOR_EMAIL);` is not working this way anymore due to new parameter you have introduced to pass custom data. This statement will give you no syntax or compilation errors, but runtime error I have mentioned in above comments.

As I don't have any custom data to be passed, below statement worked.

`Livechat.beginChat(LICENSE_NO, GROUP_ID, VISITOR_NAME, VISITOR_EMAIL, {});`  added empty curly braces for the last argument, omitting that argument or passing `null` will not fix.

Thanks for your attention.

**Comment by Mastersam07** [comment]
Thanks, @sandunangelo. I will add this to the documentation. However, I will properly address this issue.
