### ISSUE TITLE
Constructed URL response always shows Connection Lost

### ISSUE THREAD

**Issue by navneetdhameliya** [Mastersam07/livechat#24]
Hello @Mastersam07 Developers please help me to get out of this issue 
When i'm using this package after login in livechat.com it shows always Connection lost i'm adding this video please tell me if you need other information Please reply ASAP it's very urgent task for me

https://user-images.githubusercontent.com/93118368/156705966-e94f0591-e7c1-4e6a-830a-06cabbde8865.mp4

**Comment by Mastersam07** [comment]
@navneetdhameliya sorry for the late response. How are you calling the plugin?

Can you try:

`Livechat.beginChat(LICENSE_NO, GROUP_ID, VISITOR_NAME, VISITOR_EMAIL, {});` where {} is for empty or no custom params.

**Comment by ProFive** [comment]
The same problem https://ibb.co/6N5gqdN

**Comment by thanhnhan111093** [comment]
Same problem

**Comment by walvespit** [comment]
any news? same problem here

**Comment by Mastersam07** [comment]
I have not been able to replicate this. Maybe @navneetdhameliya can provide insight as they closed this issue as completed.

@walvespit is the issue happening on android or iOS for you? If android, have you added internet permission to your android manifest?

**Comment by walvespit** [comment]
> 

It is happening on iOS only
