### ISSUE TITLE
Not work in iOS

### ISSUE THREAD

**Issue by kleberandrade** [Mastersam07/livechat#25]
Dear,

I have LiveChat working on Android, but it doesn't work on iOS. When clicking the button to open LiveChat, the application closes.

Flutter: 2.10.3
LiveChat: 1.4.0

All info.pList and Podfile settings have been done.

Best Regards

**Comment by Mastersam07** [comment]
Hello @kleberandrade how are you calling the plugin?

Can you try:

`Livechat.beginChat(LICENSE_NO, GROUP_ID, VISITOR_NAME, VISITOR_EMAIL, {});`

**Comment by kleberandrade** [comment]
Yes, I just don't pass this empty brace {}, I'll test it.

`

Livechat.beginChat(
      AppEnvParams.liveChatLicense,
      AppEnvParams.liveChatGroupId,
      controller.name,
      controller.email,
    );
`

**Comment by Mastersam07** [comment]
Let me know if that works

**Comment by kleberandrade** [comment]
Follow me function

```
  Future<void> _openLiveChat() async {
    AnalyticsHelper.trackEvent(
      'chat',
      {
        'name': controller.name,
        'email': controller.email,
      },
    );

    Livechat.beginChat(
      AppEnvParams.liveChatLicense,
      AppEnvParams.liveChatGroupId,
      controller.name,
      controller.email,
      {},
    );
  }
```

When clicking on the button to open the chat, on iOS, the application closes and presents the following error.

```
flutter: -- BiometricModule INITIALIZED
flutter: -- SplashModule DISPOSED
flutter: -- HomeModule INITIALIZED
flutter: -- BiometricModule DISPOSED
flutter: -- FaqModule INITIALIZED
Could not cast value of type 'NSNull' (0x1f2ac3c60) to 'NSDictionary' (0x1f2ac3800).
Could not cast value of type 'NSNull' (0x1f2ac3c60) to 'NSDictionary' (0x1f2ac3800).
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001ba8069e8 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1ba8069e8 <+8>:  b.lo   0x1ba806a04               ; <+36>
    0x1ba8069ec <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1ba8069f0 <+16>: mov    x29, sp
    0x1ba8069f4 <+20>: bl     0x1ba802670               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
```

On android it works normally.

**Comment by Mastersam07** [comment]
@kleberandrade  I will send a fix for this shortly

**Comment by kleberandrade** [comment]
Thanks @Mastersam07 . We use the plugin in the app and would not want to switch from LiveChat to another support service.

**Comment by iloveteajay** [comment]
I’m having this problem too. Is there any fix yet for this chiefs ? 🤲🏾

**Comment by Mastersam07** [comment]
This could be related to #23 . However, a more permanent fix would be shipped in coming days.

**Comment by Mastersam07** [comment]
Closing this as this had been fixed earlier.
