### ISSUE TITLE
Could not cast value of type 'NSNull' (0x1da9e7200) to 'NSDictionary'

### ISSUE THREAD

**Issue by erfanegtfi** [Mastersam07/livechat#29]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: FB33331A-FCDA-4A36-BCB8-44EB539EE5CF
CrashReporter Key:   BECEEB1E-0D1C-8B3E-D352-ECBDD0F47368
Hardware Model:      MacBookPro18,3
Process:             Runner [52925]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/89F15741-8116-4B3B-8C8F-D2A59E53E1A1/data/Containers/Bundle/Application/B78EA271-4E11-4568-A11C-F4ABEBD5D42E/Runner.app/Runner
Identifier:          com.eterex
Version:             1.0.3 (5)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [4258]
Coalition:           com.apple.CoreSimulator.SimDevice.89F15741-8116-4B3B-8C8F-D2A59E53E1A1 [1280]
Responsible Process: SimulatorTrampoline [3172]

Date/Time:           2022-07-11 18:05:18.0163 +0430
Launch Time:         2022-07-11 18:04:54.8091 +0430
OS Version:          macOS 12.2.1 (21D62)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
CoreSimulator 802.6 - Device: iPhone12 (89F15741-8116-4B3B-8C8F-D2A59E53E1A1) - Runtime: iOS 15.4 (19E240) - DeviceType: iPhone 12
Could not cast value of type 'NSNull' (0x1da9e7200) to 'NSDictionary' (0x1da9e6da8).
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
abort() called

**Comment by erfanegtfi** [comment]
I solved this by passing empty `customParams` when I called `beginChat` method. In iOS native code `customParams` is not nullable

**Comment by Mastersam07** [comment]
This is related to #23 . Follow this solution by [sandunangelo](https://github.com/sandunangelo) https://github.com/Mastersam07/livechat/issues/23#issuecomment-1049469903
