### ISSUE TITLE
How to remove email?

### ISSUE THREAD

**Issue by yenyichau** [Mastersam07/livechat#30]
Hello, i want to remove email from this plugin. Is it possible to remove everything that related to email including UI? 
Thanks.

**Comment by Mastersam07** [comment]
Email is required by LiveChat and cannot be removed from the plugin as you cant use LiveChat without supplying email @yenyichau.

**Comment by Mastersam07** [comment]
This has been treated. Email is no longer compulsory. The only required is licenseNumber.
