### ISSUE TITLE
shows couldnt load chat

### ISSUE THREAD

**Issue by abdulkash** [Mastersam07/livechat#31]
I/ChatWindowView(30617): onConsoleMessageERROR Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
I/chromium(30617): [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')", source: https://cdn.livechatinc.com/widget/static/js/iframe.65100864.chunk.js (1)

**Comment by Mastersam07** [comment]
I believe this has been fixed by livechat.
