### ISSUE TITLE
Live chat showing the "Couldn't load chat" when running application in Flutter android

### ISSUE THREAD

**Issue by variyanirav** [Mastersam07/livechat#35]
I have tried to implement Livechat using this documentation but when I try to start the live chat its showing below error,

`onConsoleMessageERROR Uncaught (in promise) Error: An error occurred. See https://github.com/styled-components/polished/blob/master/src/internalHelpers/errors.md#3 for more information.

I/chromium(17902): [INFO:CONSOLE(2)] "Uncaught (in promise) Error: An error occurred. See https://github.com/styled-components/polished/blob/master/src/internalHelpers/errors.md#3 for more information.", source: https://cdn.livechatinc.com/widget/static/js/1.814b9876.chunk.js (2)`

**Flutter version:**
Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 3.0.1 • DevTools 2.23.1

Android:
 minSdkVersion 21
 targetSdkVersion 33

Does any one have idea? what I am doing wrong here?

![Screenshot_1686829947](https://github.com/Mastersam07/livechat/assets/12271615/9e7fc236-32c1-4a68-8bc1-e177d5e9dac1)

**Comment by faiazchowdhury** [comment]
Have been facing exactly the same issue but haven't yet been able to solve it.

**Comment by Mastersam07** [comment]
Wasn't sure whats up but the native dependencies have been updated. This should work properly now.
