### ISSUE TITLE
Stuck on white screen when minimising chat window

### ISSUE THREAD

**Issue by halldorlogi** [Mastersam07/livechat#36]
I have not tested this on Android yet, but when running on iOS simulator / iOS device I seem to be unable to exit the chat window properly.

When I tap the minimise button in the top right corner, a white screen is displayed and I can not go back by any means.
Hot restarting does not help.

Only way to return to app is to kill the app and restart.

**Comment by Mastersam07** [comment]
This has been fixed @halldorlogi .
