### ISSUE TITLE
loads slowly

### ISSUE THREAD

**Issue by ifeoluwajoshua** [Mastersam07/livechat#4]
sorry please can you make the load time before the chat details collection ui display bit faster......
it shows circular loading indicators for some seconds

**Comment by CheapSmokes** [comment]
Don't think this is a plugin issue. This is an issue from livechatinc itself.

**Comment by Mastersam07** [comment]
Hello @ifeoluwajoshua , @CheapSmokes is right. The issue if from livechatinc themself. No form of optimization from the plugin would make the load time a bit faster.

**Comment by Mastersam07** [comment]
Let me know if there is anything I can help you with.

**Comment by ifeoluwajoshua** [comment]
Thanks
