### ISSUE TITLE
iOS podspec min version

### ISSUE THREAD

**Issue by CheapSmokes** [Mastersam07/livechat#5]
Just a quick one @Mastersam07, is there any reason as to why the minimum iOS version is 9.0?

**Comment by Mastersam07** [comment]
on lower versions, the chat may not work. iOS 9 is quite an old version, the last iPhone that cannot update from iOS 9 seems to be an iPhone 4S, newer ones should be possible to be upgraded. Currently, the usage of iOS 9 is considerably small as well.
