### ISSUE TITLE
iOS Pod Install issue

### ISSUE THREAD

**Issue by CheapSmokes** [Mastersam07/livechat#6]
When compiling the example for this plugin, I get the following error from the pod install and the build fails.

```
Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing LiveChat (2.0.20)
      > Copying LiveChat from
      `/Users/bobcoenradi/Library/Caches/CocoaPods/Pods/Release/LiveChat/2.0.20-
      27dae` to `Pods/LiveChat`

    -> Installing livechat (1.0.0+1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has frameworks with conflicting names:
    livechat.
```

**Comment by Mastersam07** [comment]
This seems to be some conflict between the plugin and pod. Would look into this.

**Comment by momtboy** [comment]
hi, is this bug fixed? I also met

**Comment by CheapSmokes** [comment]
The dart plugin just needs to have its name changed for this to work. The work around is to copy the code written by the author into a new folder and modifying the plugin name. Works fine after that.

**Comment by Mastersam07** [comment]
> The dart plugin just needs to have its name changed for this to work. The work around is to copy the code written by the author into a new folder and modifying the plugin name. Works fine after that.

Figured already. Would publish a new version in a few hours.

**Comment by Mastersam07** [comment]
> hi, is this bug fixed? I also met

A new version would be published soon. Kindly wait.

**Comment by CheapSmokes** [comment]
> > hi, is this bug fixed? I also met
> 
> A new version would be published soon. Kindly wait.

Awesome work. Thanks champ.

**Comment by Mastersam07** [comment]
@momtboy @CheapSmokes plugin has been renamed and now available at [Livechatt](https://pub.dev/packages/livechatt). Let me know if this issue still continues.

**Comment by Mastersam07** [comment]
Please note that the earlier one [Livechat](https://pub.dev/packages/livechat) has been labelled discontinued.

**Comment by momtboy** [comment]
> Please note that the earlier one [Livechat](https://pub.dev/packages/livechat) has been labelled discontinued.

hi，I installed 1.0.1+2, but something went wrong?  
`No podspec found for `livechatt` in `.symlinks/plugins/livechatt/ios``
